In [1]:
import pandas as pd
import numpy as np

In [ ]:
# cargar datos
df = pd.read_csv("madrid_turismo.csv")
df

,place_id,name,rating,reviews_count,lat,lng,types,price_level,query
0,ChIJO-zP-QeIQQ0RypPybBogF2I,Parque de Atracciones de Madrid,4.1,39662.0,40.411883,-3.750058,"amusement_park, establishment, point_of_intere...",NaN,tourist attractions Madrid center
1,ChIJ35PCcoQoQg0RGhxNE3_2Iak,Círculo de Bellas Artes,4.4,33457.0,40.418304,-3.696533,"art_gallery, establishment, movie_theater, poi...",NaN,tourist attractions Madrid center
2,ChIJM7u8_EkmQg0RSH-cbUX_1Yc,Matadero Madrid,4.6,31796.0,40.391945,-3.697883,"establishment, museum, point_of_interest, tour...",NaN,tourist attractions Madrid center
3,ChIJTcV2FZ8oQg0RyFE83TPKXW0,Estanque Grande del Retiro,4.7,34498.0,40.417142,-3.683901,"establishment, park, point_of_interest, touris...",NaN,tourist attractions Madrid center
4,ChIJm1TJPX4oQg0R5uFSWl5x2zU,Clock Tower of Sun Gate,4.7,263.0,40.416558,-3.703785,"establishment, point_of_interest, tourist_attr...",NaN,tourist attractions Madrid center
...,...,...,...,...,...,...,...,...,...
1358,ChIJ1f21G5EoQg0RKdq-mKlJf7o,Hotel Fénix Gran Meliá - The Leading Hotels of...,4.6,1774.0,40.426552,-3.689210,"establishment, lodging, point_of_interest",NaN,hotels Salamanca Madrid
1359,ChIJNQE548AoQg0R-XqEsuRtfKI,Dormirdcine,4.4,1605.0,40.436333,-3.679478,"establishment, lodging, point_of_interest",NaN,hotels Salamanca Madrid
1360,ChIJ-cFBQccoQg0RjqspaeIpH2I,VP Madroño,4.4,1354.0,40.435131,-3.676565,"establishment, food, lodging, point_of_interes...",NaN,hotels Salamanca Madrid
1361,ChIJb2V2OyQmQg0RFS5Xixm_2RA,Hotel NH Madrid Atocha,4.2,1712.0,40.407690,-3.689457,"establishment, lodging, point_of_interest",NaN,hotels Retiro Madrid
1362,ChIJ28OpiComQg0R9X6BArOIOHg,Hostal Xucar,3.2,107.0,40.412241,-3.700633,"establishment, lodging, point_of_interest",NaN,hostels Lavapiés Madrid

In [ ]:
# limpiar datos fuera de madrid con filtros de latitud y longitud
df = df[
    (df["lat"] >= 40.30) & (df["lat"] <= 40.55) &
    (df["lng"] >= -3.80) & (df["lng"] <= -3.55)
]

df

,place_id,name,rating,reviews_count,lat,lng,types,price_level,query
0,ChIJO-zP-QeIQQ0RypPybBogF2I,Parque de Atracciones de Madrid,4.1,39662.0,40.411883,-3.750058,"amusement_park, establishment, point_of_intere...",NaN,tourist attractions Madrid center
1,ChIJ35PCcoQoQg0RGhxNE3_2Iak,Círculo de Bellas Artes,4.4,33457.0,40.418304,-3.696533,"art_gallery, establishment, movie_theater, poi...",NaN,tourist attractions Madrid center
2,ChIJM7u8_EkmQg0RSH-cbUX_1Yc,Matadero Madrid,4.6,31796.0,40.391945,-3.697883,"establishment, museum, point_of_interest, tour...",NaN,tourist attractions Madrid center
3,ChIJTcV2FZ8oQg0RyFE83TPKXW0,Estanque Grande del Retiro,4.7,34498.0,40.417142,-3.683901,"establishment, park, point_of_interest, touris...",NaN,tourist attractions Madrid center
4,ChIJm1TJPX4oQg0R5uFSWl5x2zU,Clock Tower of Sun Gate,4.7,263.0,40.416558,-3.703785,"establishment, point_of_interest, tourist_attr...",NaN,tourist attractions Madrid center
...,...,...,...,...,...,...,...,...,...
1358,ChIJ1f21G5EoQg0RKdq-mKlJf7o,Hotel Fénix Gran Meliá - The Leading Hotels of...,4.6,1774.0,40.426552,-3.689210,"establishment, lodging, point_of_interest",NaN,hotels Salamanca Madrid
1359,ChIJNQE548AoQg0R-XqEsuRtfKI,Dormirdcine,4.4,1605.0,40.436333,-3.679478,"establishment, lodging, point_of_interest",NaN,hotels Salamanca Madrid
1360,ChIJ-cFBQccoQg0RjqspaeIpH2I,VP Madroño,4.4,1354.0,40.435131,-3.676565,"establishment, food, lodging, point_of_interes...",NaN,hotels Salamanca Madrid
1361,ChIJb2V2OyQmQg0RFS5Xixm_2RA,Hotel NH Madrid Atocha,4.2,1712.0,40.407690,-3.689457,"establishment, lodging, point_of_interest",NaN,hotels Retiro Madrid
1362,ChIJ28OpiComQg0R9X6BArOIOHg,Hostal Xucar,3.2,107.0,40.412241,-3.700633,"establishment, lodging, point_of_interest",NaN,hostels Lavapiés Madrid

In [ ]:
# añadir categoría zona a partir de las queries
zonas_dict = {
    "malasaña": "Malasaña",
    "chueca": "Chueca",
    "salamanca": "Salamanca",
    "lavapiés": "Lavapiés",
    "la latina": "La Latina",
    "chamartín": "Chamartín",
    "retiro": "Retiro",
    "center": "Centro"
}

def extraer_zona(query):
    q = str(query).lower()
    for key, value in zonas_dict.items():
        if key in q:
            return value
    return "Otros"

df["Zona"] = df["query"].apply(extraer_zona)
df

C:\Users\marta\AppData\Local\Temp\ipykernel_11964\355362136.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Zona"] = df["query"].apply(extraer_zona)

,place_id,name,rating,reviews_count,lat,lng,types,price_level,query,Zona
0,ChIJO-zP-QeIQQ0RypPybBogF2I,Parque de Atracciones de Madrid,4.1,39662.0,40.411883,-3.750058,"amusement_park, establishment, point_of_intere...",NaN,tourist attractions Madrid center,Centro
1,ChIJ35PCcoQoQg0RGhxNE3_2Iak,Círculo de Bellas Artes,4.4,33457.0,40.418304,-3.696533,"art_gallery, establishment, movie_theater, poi...",NaN,tourist attractions Madrid center,Centro
2,ChIJM7u8_EkmQg0RSH-cbUX_1Yc,Matadero Madrid,4.6,31796.0,40.391945,-3.697883,"establishment, museum, point_of_interest, tour...",NaN,tourist attractions Madrid center,Centro
3,ChIJTcV2FZ8oQg0RyFE83TPKXW0,Estanque Grande del Retiro,4.7,34498.0,40.417142,-3.683901,"establishment, park, point_of_interest, touris...",NaN,tourist attractions Madrid center,Centro
4,ChIJm1TJPX4oQg0R5uFSWl5x2zU,Clock Tower of Sun Gate,4.7,263.0,40.416558,-3.703785,"establishment, point_of_interest, tourist_attr...",NaN,tourist attractions Madrid center,Centro
...,...,...,...,...,...,...,...,...,...,...
1358,ChIJ1f21G5EoQg0RKdq-mKlJf7o,Hotel Fénix Gran Meliá - The Leading Hotels of...,4.6,1774.0,40.426552,-3.689210,"establishment, lodging, point_of_interest",NaN,hotels Salamanca Madrid,Salamanca
1359,ChIJNQE548AoQg0R-XqEsuRtfKI,Dormirdcine,4.4,1605.0,40.436333,-3.679478,"establishment, lodging, point_of_interest",NaN,hotels Salamanca Madrid,Salamanca
1360,ChIJ-cFBQccoQg0RjqspaeIpH2I,VP Madroño,4.4,1354.0,40.435131,-3.676565,"establishment, food, lodging, point_of_interes...",NaN,hotels Salamanca Madrid,Salamanca
1361,ChIJb2V2OyQmQg0RFS5Xixm_2RA,Hotel NH Madrid Atocha,4.2,1712.0,40.407690,-3.689457,"establishment, lodging, point_of_interest",NaN,hotels Retiro Madrid,Retiro
1362,ChIJ28OpiComQg0R9X6BArOIOHg,Hostal Xucar,3.2,107.0,40.412241,-3.700633,"establishment, lodging, point_of_interest",NaN,hostels Lavapiés Madrid,Lavapiés

In [ ]:
# añadir categoría turística a partir de las queries
categorias_dict = {
    "Cultura": [
        "museum", "museums",
        "art museum",
        "tourist", "tourist attraction",
        "things to do"
    ],
    
    "Food & Drink": [
        "restaurant", "restaurants",
        "tapas",
        "bar", "bars",
        "cocktail",
        "cafe", "cafes",
        "brunch"
    ],
    
    "Alojamiento": [
        "hotel", "hotels",
        "hostel", "hostels",
        "lodging"
    ]
}

def extraer_categoria(query):
    q = str(query).lower()
    
    for categoria, keywords in categorias_dict.items():
        if any(keyword in q for keyword in keywords):
            return categoria
    
    return "Otros"

df["Categoria_general"] = df["query"].apply(extraer_categoria)
df

C:\Users\marta\AppData\Local\Temp\ipykernel_11964\2479620035.py:34: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Categoria_general"] = df["query"].apply(extraer_categoria)

,place_id,name,rating,reviews_count,lat,lng,types,price_level,query,Zona,Categoria_general
0,ChIJO-zP-QeIQQ0RypPybBogF2I,Parque de Atracciones de Madrid,4.1,39662.0,40.411883,-3.750058,"amusement_park, establishment, point_of_intere...",NaN,tourist attractions Madrid center,Centro,Cultura
1,ChIJ35PCcoQoQg0RGhxNE3_2Iak,Círculo de Bellas Artes,4.4,33457.0,40.418304,-3.696533,"art_gallery, establishment, movie_theater, poi...",NaN,tourist attractions Madrid center,Centro,Cultura
2,ChIJM7u8_EkmQg0RSH-cbUX_1Yc,Matadero Madrid,4.6,31796.0,40.391945,-3.697883,"establishment, museum, point_of_interest, tour...",NaN,tourist attractions Madrid center,Centro,Cultura
3,ChIJTcV2FZ8oQg0RyFE83TPKXW0,Estanque Grande del Retiro,4.7,34498.0,40.417142,-3.683901,"establishment, park, point_of_interest, touris...",NaN,tourist attractions Madrid center,Centro,Cultura
4,ChIJm1TJPX4oQg0R5uFSWl5x2zU,Clock Tower of Sun Gate,4.7,263.0,40.416558,-3.703785,"establishment, point_of_interest, tourist_attr...",NaN,tourist attractions Madrid center,Centro,Cultura
...,...,...,...,...,...,...,...,...,...,...,...
1358,ChIJ1f21G5EoQg0RKdq-mKlJf7o,Hotel Fénix Gran Meliá - The Leading Hotels of...,4.6,1774.0,40.426552,-3.689210,"establishment, lodging, point_of_interest",NaN,hotels Salamanca Madrid,Salamanca,Alojamiento
1359,ChIJNQE548AoQg0R-XqEsuRtfKI,Dormirdcine,4.4,1605.0,40.436333,-3.679478,"establishment, lodging, point_of_interest",NaN,hotels Salamanca Madrid,Salamanca,Alojamiento
1360,ChIJ-cFBQccoQg0RjqspaeIpH2I,VP Madroño,4.4,1354.0,40.435131,-3.676565,"establishment, food, lodging, point_of_interes...",NaN,hotels Salamanca Madrid,Salamanca,Alojamiento
1361,ChIJb2V2OyQmQg0RFS5Xixm_2RA,Hotel NH Madrid Atocha,4.2,1712.0,40.407690,-3.689457,"establishment, lodging, point_of_interest",NaN,hotels Retiro Madrid,Retiro,Alojamiento
1362,ChIJ28OpiComQg0R9X6BArOIOHg,Hostal Xucar,3.2,107.0,40.412241,-3.700633,"establishment, lodging, point_of_interest",NaN,hostels Lavapiés Madrid,Lavapiés,Alojamiento

In [6]:
# Añadir score de popularidad
df["Score_popularidad"] = df["rating"] * np.log1p(df["reviews_count"])

p1 = df["Score_popularidad"].quantile(0.01)
p99 = df["Score_popularidad"].quantile(0.99)

df["Score_popularidad_clip"] = df["Score_popularidad"].clip(p1, p99)

df["Score_popularidad_norm"] = 1 + 9 * (
    (df["Score_popularidad_clip"] - p1) / (p99 - p1)
)

df = df.drop(columns=["Score_popularidad_clip"], axis=1)

C:\Users\marta\AppData\Local\Temp\ipykernel_11964\2124729893.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Score_popularidad"] = df["rating"] * np.log1p(df["reviews_count"])
C:\Users\marta\AppData\Local\Temp\ipykernel_11964\2124729893.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Score_popularidad_clip"] = df["Score_popularidad"].clip(p1, p99)
C:\Users\marta\AppData\Local\Temp\ipykernel_11964\2124729893.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Score_popularidad_norm"] = 1 + 9 * (

In [ ]:
# cálculo de densidad por zona
df["Densidad"] = df.groupby("Zona")["place_id"].transform("count")
df

,place_id,name,rating,reviews_count,lat,lng,types,price_level,query,Zona,Categoria_general,Score_popularidad,Score_popularidad_norm,Densidad
0,ChIJO-zP-QeIQQ0RypPybBogF2I,Parque de Atracciones de Madrid,4.1,39662.0,40.411883,-3.750058,"amusement_park, establishment, point_of_intere...",NaN,tourist attractions Madrid center,Centro,Cultura,43.411514,8.949629,212
1,ChIJ35PCcoQoQg0RGhxNE3_2Iak,Círculo de Bellas Artes,4.4,33457.0,40.418304,-3.696533,"art_gallery, establishment, movie_theater, poi...",NaN,tourist attractions Madrid center,Centro,Cultura,45.839403,9.451370,212
2,ChIJM7u8_EkmQg0RSH-cbUX_1Yc,Matadero Madrid,4.6,31796.0,40.391945,-3.697883,"establishment, museum, point_of_interest, tour...",NaN,tourist attractions Madrid center,Centro,Cultura,47.688785,9.833557,212
3,ChIJTcV2FZ8oQg0RyFE83TPKXW0,Estanque Grande del Retiro,4.7,34498.0,40.417142,-3.683901,"establishment, park, point_of_interest, touris...",NaN,tourist attractions Madrid center,Centro,Cultura,49.108822,10.000000,212
4,ChIJm1TJPX4oQg0R5uFSWl5x2zU,Clock Tower of Sun Gate,4.7,263.0,40.416558,-3.703785,"establishment, point_of_interest, tourist_attr...",NaN,tourist attractions Madrid center,Centro,Cultura,26.206961,5.394189,212
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1358,ChIJ1f21G5EoQg0RKdq-mKlJf7o,Hotel Fénix Gran Meliá - The Leading Hotels of...,4.6,1774.0,40.426552,-3.689210,"establishment, lodging, point_of_interest",NaN,hotels Salamanca Madrid,Salamanca,Alojamiento,34.415156,7.090470,167
1359,ChIJNQE548AoQg0R-XqEsuRtfKI,Dormirdcine,4.4,1605.0,40.436333,-3.679478,"establishment, lodging, point_of_interest",NaN,hotels Salamanca Madrid,Salamanca,Alojamiento,32.478608,6.690269,167
1360,ChIJ-cFBQccoQg0RjqspaeIpH2I,VP Madroño,4.4,1354.0,40.435131,-3.676565,"establishment, food, lodging, point_of_interes...",NaN,hotels Salamanca Madrid,Salamanca,Alojamiento,31.730850,6.535739,167
1361,ChIJb2V2OyQmQg0RFS5Xixm_2RA,Hotel NH Madrid Atocha,4.2,1712.0,40.407690,-3.689457,"establishment, lodging, point_of_interest",NaN,hotels Retiro Madrid,Retiro,Alojamiento,31.273206,6.441164,143
1362,ChIJ28OpiComQg0R9X6BArOIOHg,Hostal Xucar,3.2,107.0,40.412241,-3.700633,"establishment, lodging, point_of_interest",NaN,hostels Lavapiés Madrid,Lavapiés,Alojamiento,14.982820,3.074642,161

In [ ]:
# guardar dataset
df.to_csv("madrid_turismo_enriched.csv", index=False, sep=";", decimal=",", encoding="utf-8")